name: rxdart_codemod
description: A collection of codemods to upgrade your RxDart code from one version to the next
version: 0.1.0
homepage: https://github.com/brianegan/rxdart_codmod
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  codemod: ^0.1.5
  args: ^1.5.1
  source_span: ^1.4.1


executables:
  codemod_rxdart_22_to_23:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  coverage: ">=0.13.0 <0.14.0"
