name: rxdart_codemod
description: A collection of codemods to upgrade your RxDart code from one version to the next
version: 0.1.2
homepage: https://github.com/brianegan/rxdart_codmod
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  analyzer: '>=0.37.0 <0.39.0'
  codemod: '>=0.1.5 <0.2.0'
  args: '>=1.5.1 <2.0.0'
  source_span: '>=1.4.1 <2.0.0'

executables:
  22_to_23:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  coverage: ">=0.13.0 <0.14.0"
